### ISSUE TITLE
Failed to build Petalinux Project with Ubuntu 20.04

### ISSUE THREAD

**Issue by 71lovecodes** [prophesee-ai/petalinux-projects#1]
We are trying to follow the step-by-step guide for compiling this petalinux project. However, we get the error below. It seems related to the cmake version, however, in the system we have cmake 3.24 , but bitbake seems to complain about  this... something in the sophus package? can somebody please help debug this issue? See the log below.

many thanks!
Xueqi & Team

#######################

State summary: Wanted 4530 Local 0 Network 2198 Missed 2332 Current 0 (48% match, 0% complete)
NOTE: Executing Tasks
ERROR: sophus-1.24.6-r0 do_configure: ExecutionError('/home/xueqi/petalinux-projects/build/tmp/work/cortexa72-cortexa53-xilinx-linux/sophus/1.24.6-r0/temp/run.do_configure.3529508', 1, None, None)
ERROR: Logfile of failure stored in: /home/xueqi/petalinux-projects/build/tmp/work/cortexa72-cortexa53-xilinx-linux/sophus/1.24.6-r0/temp/log.do_configure.3529508
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/home/xueqi/petalinux-projects/components/yocto/layers/core/meta/recipes-core/glibc/glibc_2.34.bb:do_populate_sysroot', '/home/xueqi/petalinux-projects/components/yocto/layers/meta-openembedded/meta-oe/recipes-support/libeigen/libeigen_3.4.0.bb:do_populate_sysroot', '/home/xueqi/petalinux-projects/components/yocto/layers/core/meta/recipes-devtools/cmake/cmake-native_3.21.1.bb:do_populate_sysroot', '/home/xueqi/petalinux-projects/components/yocto/layers/core/meta/recipes-devtools/quilt/quilt-native_0.66.bb:do_populate_sysroot', '/home/xueqi/petalinux-projects/components/yocto/layers/core/meta/recipes-devtools/gcc/gcc-cross_11.2.bb:do_populate_sysroot', 'virtual:native:/home/xueqi/petalinux-projects/components/yocto/layers/core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/home/xueqi/petalinux-projects/components/yocto/layers/core/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', 'virtual:native:/home/xueqi/petalinux-projects/components/yocto/layers/core/meta/recipes-devtools/ninja/ninja_1.10.2.bb:do_populate_sysroot', '/home/xueqi/petalinux-projects/components/yocto/layers/core/meta/recipes-devtools/gcc/gcc-runtime_11.2.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['glibc', 'libeigen', 'cmake-native', 'quilt-native', 'gcc-cross-aarch64', 'pseudo-native', 'patch-native', 'ninja-native', 'gcc-runtime', 'linux-libc-headers', 'binutils-cross-aarch64', 'texinfo-dummy-native', 'flex-native', 'autoconf-native', 'mpfr-native', 'libtool-native', 'gnu-config-native', 'zlib-native', 'automake-native', 'libmpc-native', 'xz-native', 'gmp-native', 'ncurses-native', 'bzip2-native', 'curl-native', 'zstd-native', 'attr-native', 're2c-native', 'libgcc', 'pkgconfig-native', 'gettext-minimal-native', 'm4-native', 'openssl-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_configure
| CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
|   CMake 3.24 or higher is required.  You are running version 3.21.1
| 
| 
| -- Configuring incomplete, errors occurred!
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/xueqi/petalinux-projects/project-spec/meta-user/recipes-support/sophus/sophus_1.24.6.bb:do_configure) failed with exit code '1'

**Comment by 71lovecodes** [comment]
This issue seems related to the fact that the petalinux project is trying to compile cmake-3.21.. see screenshot..

![Screenshot from 2024-10-02 18-21-47](https://github.com/user-attachments/assets/bea6b4a7-95fe-453a-90b8-dfd22e88d8d5)

**Comment by federicohyo** [comment]
This issue is related the Petalinux version 2022.2. If you use petalinux 2022.2, you should update the cmake version with the https://github.com/yoctoproject/poky/tree/yocto-5.0.3/meta/recipes-devtools/cmake (version [cmake-native_3.28.3.bb]). Then compile, and it will work!
