### ISSUE TITLE
Errors while loading and set the pipeline with the default script

### ISSUE THREAD

**Issue by federicohyo** [prophesee-ai/petalinux-projects#2]
Wer manage to compile the petalinux project, however, we have the following error when executing the load-prophesee-kv260-imx636.sh script.

This seems related to the petalinux project and the kernels module.

Can someone please help debugging this issue? Many thanks!

![prophesee_error](https://github.com/user-attachments/assets/95cf76c4-b721-4d26-98b6-c747450b0d8c)

**Comment by lbristiel-psee** [comment]
Hello @federicohyo,

sorry for the felay to come back to you.
those errors are related to a Xilinx driver that we don't actually use, so they can be safely ignored.

Laurent from Prophesee Support
